name: Deploy

on:
  push:
    branches:
      - main

jobs:
  update_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_ENV }}
          REMOTE_HOST: ${{ secrets.SSH_HOST_ENV }}
          REMOTE_USER: ${{ secrets.SSH_USER_ENV }}
          TARGET: ${{ secrets.REMOTE_DIR_ENV }}
